{% set name = "kedro-datasets" %}
{% set version = "9.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 444d1f769ae87056c47ebe2c72c9a7d56fafafb4033a1e78677043e96fdeacc0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONWARNINGS="ignore::UserWarning"

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - backports.strenum
    - kedro >=1.0.0rc1,<2.0.0
    - lazy_loader

test:
  imports:
    - kedro_datasets
    - kedro_datasets_experimental
  commands:
    - pip check # kedro 0.18.11 has requirement pip-tools~=6.5, but you have pip-tools 7.1.0
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets
  summary: Kedro-Datasets is where you can find all of Kedro's data connectors.
  dev_url: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
