{% set name = "kedro-datasets" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 56e67fdc9cd7670a811407c471b0c7d98e81daaa66043ff052f0a0b0b6b2d4af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONWARNINGS="ignore::UserWarning"

requirements:
  host:
    - python >=3.9
    - setuptools >=61.2
    - pip
  run:
    - python >=3.9
    - kedro >=0.19
    - lazy_loader

test:
  imports:
    - kedro_datasets
  commands:
    - pip check # kedro 0.18.11 has requirement pip-tools~=6.5, but you have pip-tools 7.1.0
  requires:
    - pip

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets
  summary: Kedro-Datasets is where you can find all of Kedro's data connectors.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
