{% set name = "kedro-datasets" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro-datasets-{{ version }}.tar.gz
  sha256: dc99e8409667e3a8e73410c9c85f47075330197c9aa27eec7c9365a6a515bf37

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - setuptools >=61.2
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - kedro >=0.18.4,<0.19.0

test:
  imports:
    - kedro_datasets

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets
  summary: Kedro-Datasets is where you can find all of Kedro's data connectors.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
