{% set name = "kedro-datasets" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6dc964d4b60bab89c9836044fe2a027676395acac610a1500a4727036c38a3c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONWARNINGS="ignore::UserWarning"

requirements:
  host:
    - python >=3.9
    - setuptools >=61.2
    - pip
  run:
    - lazy-loader
    - python >=3.9
    - kedro >=0.19.7
    - lazy_loader

test:
  imports:
    - kedro_datasets
  commands:
    - pip check # kedro 0.18.11 has requirement pip-tools~=6.5, but you have pip-tools 7.1.0
  requires:
    - pip

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets
  summary: Kedro-Datasets is where you can find all of Kedro's data connectors.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
